### ISSUE TITLE
to Start, Quick start ?

### ISSUE THREAD

**Issue by fwt-dot-fr** [Kanstantsin-Y/GNSS_RTCM_DECODER#1]
Run main.py with command line arguments to start conversion. See [Home](https://github.com/Kanstantsin-Y/GNSS_RTCM_DECODER/blob/main/DOCs/Home.md) for details.

Run main.py with command line arguments to start conversion. See [Home](https://github.com/Kanstantsin-Y/GNSS_RTCM_DECODER/blob/main/DOCs/Home.md) for details.

>>>py start_decoder.py --help
usage: Convert some RTCM files [-h] [-o FORMAT] [-i PATH] [-v] [-ext EXT] SRC [SRC ...]

?-> No start_decoder.py

root@dev1:~/GNSS_RTCM_DECODER# python3 main.py
Traceback (most recent call last):
  File "/root/GNSS_RTCM_DECODER/main.py", line 19, in <module>
    from controls import ConverterControls
  File "/root/GNSS_RTCM_DECODER/controls.py", line 10, in <module>
    from printers import MargoControls
ImportError: cannot import name 'MargoControls' from 'printers' (unknown location)

?-> What conf to do ?

**Comment by Kanstantsin-Y** [comment]
Uncomment line 314 in main.py (see attachment). And run main.py without
arguments for test launch.
Script was developed and tested in the Windows environment, Phython 3.10.8.
Use '/' in file path for Linux.


чт, 2 мар. 2023 г. в 20:41, Museux ***@***.***>:

**Comment by fwt-dot-fr** [comment]
No attachment found
do:
ARGS = r"-o JSON RTCM3_TEST_DATA/reference-3msg.rtcm3"
ARGS = r"-i addons.ini RTCM3_TEST_DATA/reference-3msg.rtcm3"
#ARGS = None

Failed.

Same thing with Thonny 4.02 and Windows 10.

Python 3.10.9 (C:\Program Files (x86)\Thonny\python.exe)

>>> %Run main.py
Traceback (most recent call last):
  File "E:\Documents\!Gnss\Logiciels\RTCM\GNSS_RTCM_DECODER\GNSS_RTCM_DECODER-main\main.py", line 19, in <module>
    from controls import ConverterControls
  File "E:\Documents\!Gnss\Logiciels\RTCM\GNSS_RTCM_DECODER\GNSS_RTCM_DECODER-main\controls.py", line 10, in <module>
    from printers import MargoControls
ImportError: cannot import name 'MargoControls' from 'printers' (unknown location)
>>>

**Comment by Elhorses** [comment]
hi, guys, I have happened these questions, and can you help me reserve these questions? 
thanks!

**Comment by Elhorses** [comment]
hi, guys, I have happened these questions, and can you help me solve these questions?
thanks!

**Comment by Kanstantsin-Y** [comment]
Please, describe properly your situation. You can also send me a file (link, if it is too big) you tried to convert. I will check it.
Also, I am not a Linux user. I can not test the utility in Linux environments.

**Comment by Kanstantsin-Y** [comment]
You can try to relocate your project to another place. Create simple path, like "D:RTCM\Converter\main.py" without special symbols.

**Comment by Elhorses** [comment]
> 

I'll try it, thanks for your help
